#!/bin/bash
apt-get update
apt-get install docker docker.io -y
docker volume create --name ovpn-data-dir
export IP_ADDRESS=$(ifconfig eth0 | grep "inet " | awk '{print $2}')
docker run -v ovpn-data-dir:/etc/openvpn --log-driver=none --rm kylemanna/openvpn ovpn_genconfig -u udp://${IP_ADDRESS}
docker run -v ovpn-data-dir:/etc/openvpn --log-driver=none --rm kylemanna/openvpn /bin/bash -c "easyrsa init-pki"
docker run -v ovpn-data-dir:/etc/openvpn --log-driver=none --rm kylemanna/openvpn /bin/bash -c "easyrsa --batch --req-cn=${IP_ADDRESS} build-ca nopass"
docker run -v ovpn-data-dir:/etc/openvpn --log-driver=none --rm kylemanna/openvpn /bin/bash -c "easyrsa gen-dh"
docker run -v ovpn-data-dir:/etc/openvpn --log-driver=none --rm kylemanna/openvpn /bin/bash -c "openvpn --genkey --secret /etc/openvpn/pki/ta.key"
docker run -v ovpn-data-dir:/etc/openvpn --log-driver=none --rm kylemanna/openvpn /bin/bash -c "easyrsa build-server-full ${IP_ADDRESS} nopass"
docker run -v ovpn-data-dir:/etc/openvpn -d -p 1194:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn
docker run -v ovpn-data-dir:/etc/openvpn --log-driver=none --rm kylemanna/openvpn easyrsa build-client-full tmpvpn nopass
docker run -v ovpn-data-dir:/etc/openvpn --log-driver=none --rm kylemanna/openvpn ovpn_getclient tmpvpn > /tmp/tmpvpn.ovpn